const trainsong = [
  {
    title: 'The Path',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'lBZ3gfaMQVI',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Atlas Stone',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'YZ8v_evgiS4',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Cockroach King',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'tUa14ly7N8M',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'In Memoriam',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: '3NdXqroDz9c',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Because It\'s There',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: '65020NiNR8o',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Falling Back To Earth',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: '9XKPW0XVXe4',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'As Death Embraces',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'yKwHxGGzP80',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Pareidolia',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: '3HciKwoVAvo',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Somebody',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'sv-cCGfndqc',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'The Path Unbeaten',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'cwXVTChl0Tg',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'Nobody',
    artist: 'Haken',
    album: 'The Mountain',
    youtubeID: 'qKBMfiOHZvg',
    albumart: 'albumart/TheMountain.jpg',
  },
  {
    title: 'The Point of No Return',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'rTJiHkaHA84',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Streams',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'B3WAxBI1CBc',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Aquarium',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'mZJ8O4qmfYw',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Eternal Rain',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'Fg2HV59PDZ0',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Drowning in the Flood',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'ai2U8Jv_Peg',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Sun',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'TMOZyslMUso',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Celestial Elixir',
    artist: 'Haken',
    album: 'Aquarius',
    youtubeID: 'mdh6upXZL6c',
    albumart: 'albumart/Aquarius.jpg',
  },
  {
    title: 'Premonition',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'dIaV6se5n44',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Nocturnal Conspiracy',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'VYldDOGERxU',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Insomnia',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: '0gpG_HDfo2c',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'The Mind\'s Eye',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'ttGqISdVJJE',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Portals',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'QyPmxaZVFOo',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Shapeshifter',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'AST8rFjPIp4',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Deathless',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'D_NVVWhfiRw',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Visions',
    artist: 'Haken',
    album: 'Visions',
    youtubeID: 'rSyfvnF5pps',
    albumart: 'albumart/Visions.jpg',
  },
  {
    title: 'Scissorlips',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'amYzfRbw6Aw',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Turning Sheep into Goats',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'BEPf86o3YvA',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Systematomatic',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: '11zQt81IBAI',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'River of Glass',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'UcZFY8g7KNQ',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Keyhole in the Sky',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'h38Qn--kfoU',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Downhill',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'wMEuDbCKdbk',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Feathergun in the Garden of the Sun',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'TBYOgS7USGk',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Dreamcatcher',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'vLICxG1acDU',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Diamond Eyes',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'b84Ihsz5Q7M',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Katsushika',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: '3CHBN7xGTrs',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'Weevil Bride',
    artist: 'Rishloo',
    album: 'Feathergun',
    youtubeID: 'S7q2CocZWnQ',
    albumart: 'albumart/feathergun.jpg',
  },
  {
    title: 'The Great Rain Beatle',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'rZeIjlsKbao',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Landmines',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'mMle586mIfc',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Dead Rope Machine',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'hLPld5mtdQ4',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Dark Charade',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'gdFoHdAIOQE',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Salutations',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'EZrfyWbX47g',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Radio',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'm8dFz2I5mFM',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Winslow',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: '0NAb7iGBw20',
    albumart: 'albumart/livingasghosts.jpg',
  },
  {
    title: 'Just a Ride',
    artist: 'Rishloo',
    album: 'Living as Ghosts With Buildings as Teeth',
    youtubeID: 'zmvKewDOnnU',
    albumart: 'albumart/livingasghosts.jpg',
  },
];
exports.trainsong = trainsong;

const boop = [
// maybe later
];
exports.boop = boop;